version: "3"

services:
  user-service:
    build:
      context: /user-service
      dockerfile: /Dockerfile
    ports:
    - 8081:8081

  department-service:
    build:
      context: /department-service
      dockerfile: /Dockerfile
    ports:
    - 8082:8082
    depends_on:
    - user-service
  krakend_ce:
    build:
      context: .
      dockerfile: Dockerfile
    image: devopsfaith/krakend:2.1.3
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"